version: '3.7'

services:
  db:
    image: postgres:14-bullseye
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    expose:
      - '5432'
    networks:
      - interconnect
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    entrypoint: ["/start.sh"]
    ports:
      - 8000:8000
    networks:
      - interconnect

volumes:
  pgdata:

networks:
  interconnect:
    driver: bridge