# Generated by Django 3.2 on 2023-12-16 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('name', models.CharField(max_length=255, verbose_name='Brand name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractsApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('application_number', models.CharField(max_length=255, verbose_name='contract_number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('brand_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_ids', to='contracts.brands')),
                ('contract_application_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_ids', to='contracts.contractsapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('contract_number', models.CharField(max_length=255, verbose_name='Contract number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('contract_application_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_id', to='contracts.contractsapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
