# Generated by Django 3.2 on 2023-12-17 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='contract_application_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='contract_application_id',
        ),
        migrations.AddField(
            model_name='contractsapplication',
            name='contract_application_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_application_id', to='contracts.contracts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractsapplication',
            name='product_ids',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_application_id', to='contracts.products'),
            preserve_default=False,
        ),
    ]
