# Generated by Django 3.2 on 2023-12-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20231217_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractsapplication',
            name='product_ids',
        ),
        migrations.AddField(
            model_name='contractsapplication',
            name='product_ids',
            field=models.ManyToManyField(related_name='contract_application_ids', to='contracts.Products'),
        ),
    ]
