# Generated by Django 3.2 on 2023-12-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20231223_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Brand name'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='contract_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Contract number'),
        ),
        migrations.AlterField(
            model_name='contractsapplication',
            name='application_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='contract_number'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ids', to='contracts.brands'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Product name'),
        ),
    ]
